<?php

$RING_FAMILY_GROUP = array(
		RING_GROUP_INSERT
		,RING_GROUP_SAVE
		,RING_GROUP_DELETE
		,RING_GROUP_DEFAULT
	);
$RING_NAME[RING_GROUP_INSERT]		= '新增';
$RING_NAME[RING_GROUP_SAVE]		= '編輯';
$RING_NAME[RING_GROUP_DELETE]		= '刪除';
$RING_NAME[RING_GROUP_DEFAULT]		= '預設';


$RING_FAMILY_STAFF = array(
		RING_STAFF_INSERT
		,RING_STAFF_SAVE
		,RING_STAFF_DELETE
		,RING_STAFF_CHANGE_PWD
		,RING_STAFF_CHANGE_GRP
	);
$RING_NAME[RING_STAFF_INSERT]		= '新增';
$RING_NAME[RING_STAFF_SAVE]		= '編輯';
$RING_NAME[RING_STAFF_DELETE]		= '刪除';
$RING_NAME[RING_STAFF_CHANGE_PWD]	= '修改密碼';
$RING_NAME[RING_STAFF_CHANGE_GRP]	= '修改族群';


$RING_FAMILY_CATEGORY = array(
		RING_CATEGORY_INSERT
		,RING_CATEGORY_SAVE
		,RING_CATEGORY_DELETE
	);
$RING_NAME[RING_CATEGORY_INSERT]	= '新增';
$RING_NAME[RING_CATEGORY_SAVE]		= '編輯';
$RING_NAME[RING_CATEGORY_DELETE]	= '刪除';


$RING_FAMILY_CASE = array(
		RING_CASE_INSERT
		,RING_CASE_SAVE
		,RING_CASE_DELETE
		,RING_CASE_TAKE
		,RING_CASE_RETURN
		,RING_CASE_CLOSE
		,RING_ARCHIVE_SAVE
		,RING_ARCHIVE_DELETE
	);
$RING_NAME[RING_CASE_INSERT]		= '新增';
$RING_NAME[RING_CASE_SAVE]		= '編輯';
$RING_NAME[RING_CASE_DELETE]		= '刪除';
$RING_NAME[RING_CASE_TAKE]		= '接手';
$RING_NAME[RING_CASE_RETURN]		= '退回';
$RING_NAME[RING_CASE_CLOSE]		= '結束';
$RING_NAME[RING_ARCHIVE_SAVE]		= '編輯歸檔';
$RING_NAME[RING_ARCHIVE_DELETE]		= '刪除歸檔';


$RING_FAMILY_CLIENT = array(
		RING_CLIENT_INSERT
		,RING_CLIENT_SAVE
		,RING_CLIENT_DELETE
		,RING_CLIENT_ATTACHMENTS
	);
$RING_NAME[RING_CLIENT_INSERT]		= '新增';
$RING_NAME[RING_CLIENT_SAVE]		= '編輯';
$RING_NAME[RING_CLIENT_DELETE]		= '刪除';
$RING_NAME[RING_CLIENT_ATTACHMENTS]	= '附件';


$RING_FAMILY_SUPPLIER = array(
		RING_SUPPLIER_INSERT
		,RING_SUPPLIER_SAVE
		,RING_SUPPLIER_DELETE
		,RING_SUPPLIER_ATTACHMENTS
	);
$RING_NAME[RING_SUPPLIER_INSERT]	= '新增';
$RING_NAME[RING_SUPPLIER_SAVE]		= '編輯';
$RING_NAME[RING_SUPPLIER_DELETE]	= '刪除';
$RING_NAME[RING_SUPPLIER_ATTACHMENTS]	= '附件';


$RING_FAMILY_STANDBY = array(
		RING_STANDBY_INSERT
		,RING_STANDBY_SAVE
		,RING_STANDBY_DELETE
		,RING_STANDBY_ATTACHMENTS
	);
$RING_NAME[RING_STANDBY_INSERT]		= '新增';
$RING_NAME[RING_STANDBY_SAVE]		= '編輯';
$RING_NAME[RING_STANDBY_DELETE]		= '刪除';
$RING_NAME[RING_STANDBY_ATTACHMENTS]	= '附件';


$RING_FAMILY_EXPIRED = array(
		RING_EXPIRED_INSERT
		,RING_EXPIRED_SAVE
		,RING_EXPIRED_DELETE
		,RING_EXPIRED_ATTACHMENTS
	);
$RING_NAME[RING_EXPIRED_INSERT]		= '新增';
$RING_NAME[RING_EXPIRED_SAVE]		= '編輯';
$RING_NAME[RING_EXPIRED_DELETE]		= '刪除';
$RING_NAME[RING_EXPIRED_ATTACHMENTS]	= '附件';


$RING_FAMILY_SALE = array(
		RING_SALE_INSERT
		,RING_SALE_SAVE
		,RING_SALE_DELETE
		,RING_SALE_ATTACHMENTS
	);
$RING_NAME[RING_SALE_INSERT]		= '新增';
$RING_NAME[RING_SALE_SAVE]		= '編輯';
$RING_NAME[RING_SALE_DELETE]		= '刪除';
$RING_NAME[RING_SALE_ATTACHMENTS]	= '附件';


$RING_FAMILY_LEND = array(
		RING_LEND_INSERT
		,RING_LEND_SAVE
		,RING_LEND_DELETE
		,RING_LEND_ATTACHMENTS
		,RING_LEND_RETURN
	);
$RING_NAME[RING_LEND_INSERT]		= '新增';
$RING_NAME[RING_LEND_SAVE]		= '編輯';
$RING_NAME[RING_LEND_DELETE]		= '刪除';
$RING_NAME[RING_LEND_ATTACHMENTS]	= '附件';
$RING_NAME[RING_LEND_RETURN]		= '歸還';


$RING_FAMILY_OUT = array(
		RING_OUT_INSERT
		,RING_OUT_SAVE
		,RING_OUT_DELETE
		,RING_OUT_ATTACHMENTS
	);
$RING_NAME[RING_OUT_INSERT]		= '新增';
$RING_NAME[RING_OUT_SAVE]		= '編輯';
$RING_NAME[RING_OUT_DELETE]		= '刪除';
$RING_NAME[RING_OUT_ATTACHMENTS]	= '附件';


$RING_FAMILY_REPAIR = array(
		RING_REPAIR_INSERT
		,RING_REPAIR_SAVE
		,RING_REPAIR_DELETE
		,RING_REPAIR_ATTACHMENTS
		,RING_REPAIR_RETURN
		,RING_REPAIR_ARCHIVE_SAVE
		,RING_REPAIR_ARCHIVE_DELETE
	);
$RING_NAME[RING_REPAIR_INSERT]		= '新增';
$RING_NAME[RING_REPAIR_SAVE]		= '編輯';
$RING_NAME[RING_REPAIR_DELETE]		= '刪除';
$RING_NAME[RING_REPAIR_ATTACHMENTS]	= '附件';
$RING_NAME[RING_REPAIR_RETURN]		= '取回';
$RING_NAME[RING_REPAIR_ARCHIVE_SAVE]	= '編輯歸檔';
$RING_NAME[RING_REPAIR_ARCHIVE_DELETE]	= '刪除歸檔';


$RING_FAMILY_FILE = array(
		RING_FILE_INSERT
		,RING_FILE_SAVE
		,RING_FILE_DELETE
		,RING_FILE_ATTACHMENTS
	);
$RING_NAME[RING_FILE_INSERT]		= '新增';
$RING_NAME[RING_FILE_SAVE]		= '編輯';
$RING_NAME[RING_FILE_DELETE]		= '刪除';
$RING_NAME[RING_FILE_ATTACHMENTS]	= '附件';


$RING_FAMILY_MARK = array(
		RING_MARK_INSERT
		,RING_MARK_SAVE
		,RING_MARK_DELETE
		,RING_MARK_ATTACHMENTS
	);
$RING_NAME[RING_MARK_INSERT]		= '新增';
$RING_NAME[RING_MARK_SAVE]		= '編輯';
$RING_NAME[RING_MARK_DELETE]		= '刪除';
$RING_NAME[RING_MARK_ATTACHMENTS]	= '附件';

?>