<?php

if (empty($_GET['group_id'])) SHOW_ERROR(ERROR_ARGUMENTS);

if (get_magic_quotes_gpc()) {
	$_GET['group_id'] = stripslashes($_GET['group_id']);
}

$group_id = RETURN_ID_FROM($_GET['group_id']);
CHECK_ID_EXIST($group_id, $ROWS, $ri);
$row = &$ROWS[$ri];
$rings = explode(',', $row[GROUP_RING]);


HTML_HEADER('編輯族群');
MENU_BAR();

FORM_HEADER($THIS_PHP_FILE.'&op=save&group_id='.$group_id, 'CHECK_SAVE_GROUP');
	FORM_INPUT_TEXT('名稱', 'group_name', 32, $row[GROUP_NAME]);
	FORM_INPUT_ANY('案例', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_CASE));
	FORM_INPUT_ANY('送修', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_REPAIR));
	FORM_INPUT_ANY('標記', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_MARK));
	FORM_INPUT_ANY('出借', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_LEND));
	FORM_INPUT_ANY('出貨', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_SALE));
	FORM_INPUT_ANY('外派', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_OUT));
	FORM_INPUT_ANY('檔案', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_FILE));
	FORM_INPUT_ANY('過期', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_EXPIRED));
	FORM_INPUT_ANY('客戶', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_CLIENT));
	FORM_INPUT_ANY('廠商', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_SUPPLIER));
	FORM_INPUT_ANY('備品', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_STANDBY));
	FORM_INPUT_ANY('歸類', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_CATEGORY));
	FORM_INPUT_ANY('員工', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_STAFF));
	FORM_INPUT_ANY('族群', RETURN_GROUP_FAMILY($rings, $RING_FAMILY_GROUP));
FORM_FOOTER(!empty($THIS_STAFF_RINGS[RING_GROUP_SAVE]), '儲存');


HTML_OUTPUT();

?>